### ISSUE TITLE
Crash when open the about windows in menu

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/dtkcore#35]
The backtrace:

```
(gdb) bt

#0  0x00007ffff78282f3 in Dtk::Core::DDesktopEntry::rawValue(QString const&, QString const&, QString const&) const () from /usr/lib64/libdtkcore.so.5
linuxdeepin/deepin-movie-reborn#1  0x00007ffff782952f in Dtk::Core::DDesktopEntry::stringValue(QString const&, QString const&, QString const&) const () from /usr/lib64/libdtkcore.so.5
linuxdeepin/deepin-movie-reborn#2  0x00007ffff782c9db in Dtk::Core::DSysInfo::distributionOrgWebsite(Dtk::Core::DSysInfo::OrgType) () from /usr/lib64/libdtkcore.so.5
linuxdeepin/deepin-movie-reborn#3  0x00007ffff7a2a998 in Dtk::Widget::DAboutDialogPrivate::loadDistributionInfo() () from /usr/lib64/libdtkwidget.so.5
linuxdeepin/deepin-movie-reborn#4  0x00007ffff7a2b7f5 in Dtk::Widget::DAboutDialogPrivate::init() ()
   from /usr/lib64/libdtkwidget.so.5
linuxdeepin/deepin-movie-reborn#5  0x00007ffff7a32f0e in Dtk::Widget::DAboutDialog::DAboutDialog(QWidget*) ()
   from /usr/lib64/libdtkwidget.so.5
linuxdeepin/deepin-movie-reborn#6  0x00007ffff7a5dc28 in Dtk::Widget::DApplication::handleAboutAction() ()
   from /usr/lib64/libdtkwidget.so.5
linuxdeepin/deepin-movie-reborn#7  0x00007ffff63a6900 in ?? () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#8  0x00007ffff72b8f12 in QAction::triggered(bool) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#9  0x00007ffff72bb751 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#10 0x00007ffff7435aaa in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#11 0x00007ffff743d1e2 in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#12 0x00007ffff72ff35e in QWidget::event(QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
  ts.so.5
linuxdeepin/deepin-movie-reborn#13 0x00007ffff72bf50f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#14 0x00007ffff72c63fb in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#15 0x00007ffff63702ea in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#16 0x00007ffff72c5426 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#17 0x00007ffff7317933 in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#18 0x00007ffff731a8ce in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#19 0x00007ffff72bf50f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#20 0x00007ffff63702ea in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#21 0x00007ffff6a73b73 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
linuxdeepin/deepin-movie-reborn#22 0x00007ffff6a49c5c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
linuxdeepin/deepin-movie-reborn#23 0x00007ffff24a7fea in ?? () from /usr/lib64/libQt5XcbQpa.so.5
linuxdeepin/developer-center#1087 0x00007ffff53dde57 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#25 0x00007ffff53de1d8 in ?? () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#26 0x00007ffff53de28f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#27 0x00007ffff63c783f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#28 0x00007ffff636ecab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#29 0x00007ffff743ac0c in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#30 0x00007ffff743ad3f in QMenu::exec(QPoint const&, QAction*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#31 0x00007ffff7a82d03 in Dtk::Widget::DTitlebar::showMenu() ()
   from /usr/lib64/libdtkwidget.so.5
--Type <RET> for more, q to quit, c to continue without paging--
linuxdeepin/deepin-movie-reborn#32 0x00007ffff63a68c6 in ?? () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#33 0x00007ffff63a68c6 in ?? () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#34 0x00007ffff73ac3e2 in QAbstractButton::clicked(bool) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#35 0x00007ffff73acd4a in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#36 0x00007ffff73ae69f in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#37 0x00007ffff73ae871 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#38 0x00007ffff72ff35e in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#39 0x00007ffff72bf50f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#40 0x00007ffff72c63fb in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#41 0x00007ffff63702ea in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#42 0x00007ffff72c5426 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#43 0x00007ffff73173c1 in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#44 0x00007ffff731a8ce in ?? () from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#45 0x00007ffff72bf50f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Widgets.so.5
linuxdeepin/deepin-movie-reborn#46 0x00007ffff63702ea in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#47 0x00007ffff6a73b73 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
linuxdeepin/deepin-movie-reborn#48 0x00007ffff6a49c5c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
linuxdeepin/deepin-movie-reborn#49 0x00007ffff24a7fea in ?? () from /usr/lib64/libQt5XcbQpa.so.5
linuxdeepin/deepin-movie-reborn#50 0x00007ffff53dde57 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#51 0x00007ffff53de1d8 in ?? () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#52 0x00007ffff53de28f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
linuxdeepin/deepin-movie-reborn#53 0x00007ffff63c783f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEvent--Type <RET> for more, q to quit, c to continue without paging--
sFlag>) () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#54 0x00007ffff636ecab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib64/libQt5Core.so.5


linuxdeepin/deepin-movie-reborn#55 0x00007ffff6376f20 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
linuxdeepin/deepin-movie-reborn#56 0x000055555560d458 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/deepin-music-player-6.0.1.91-32.1.x86_64/music/music-player/main.cpp:227

```

**Comment by deepin-CD** [comment]
应该算是一个bug（在非uos上会出现）， uos是会带这个文件的， 这个文件以前是用来判断系统发行版本，但是在这个ensureDeepinInfo最后初始化了distributionInfo指针， 如果/etc/deepin-version不存在那么不会被初始化也就是空指针， 这个崩溃就是访问了空指针导致的。 临时解决办法是自己创建一个 /etc/deepin-version。 或者等 dtkcore更新也是可以的。

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
